/* INVOICES */
export const GET_SWAIREE_APPLICATIONS = "GET_SWAIREE_APPLICATIONS"
export const GET_SWAIREE_APPLICATIONS_SUCCESS = "GET_SWAIREE_APPLICATIONS_SUCCESS"
export const GET_SWAIREE_APPLICATIONS_FAIL = "GET_SWAIREE_APPLICATIONS_FAIL"

export const GET_SWAIREE_APPLICATION_DETAIL = "GET_SWAIREE_APPLICATION_DETAIL"
export const GET_SWAIREE_APPLICATION_DETAIL_SUCCESS = "GET_SWAIREE_APPLICATION_DETAIL_SUCCESS"
export const GET_SWAIREE_APPLICATION_DETAIL_FAIL = "GET_SWAIREE_APPLICATION_DETAIL_FAIL"
