/* INVOICES */
export const GET_APPLICATIONS = "GET_APPLICATIONS"
export const GET_APPLICATIONS_SUCCESS = "GET_APPLICATIONS_SUCCESS"
export const GET_APPLICATIONS_FAIL = "GET_APPLICATIONS_FAIL"

export const GET_APPLICATION_DETAIL = "GET_APPLICATION_DETAIL"
export const GET_APPLICATION_DETAIL_SUCCESS = "GET_APPLICATION_DETAIL_SUCCESS"
export const GET_APPLICATION_DETAIL_FAIL = "GET_APPLICATION_DETAIL_FAIL"
